version: "3"
services:
  aadhar-backend:
    image: chaitrarbhat/aadhar-backend-app:1.0
    ports:
      - "9090:9090"
    networks:
      - maadhar-application
  aadhar-frontend:
    image: chaitrarbhat/aadhar-frontend-app:1.0
    ports:
      - "80:80"
    depends_on:
      - aadhar-backend
    networks:
      - maadhar-application
networks:
  maadhar-application: